. "$HOME/.local/bin/env"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

. ~/z.sh

export PATH="$HOME/.gem/ruby/2.6.0/bin:$PATH"

export PATH="$HOME/.gem/ruby/$(ruby -e "print RbConfig::CONFIG[\"ruby_version\"]")/bin:$PATH"
. "$HOME/.cargo/env"
export PATH="/Library/TeX/texbin:$PATH"
